title: Permpoon Chaowanaphunphon
email: samurai.hanso@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello my friends
domain: mossnana.github.io
url: https://mossnana.github.io
baseurl: ""
url: "https://mossnana.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: permpoonchao
github_username:  mossnana
theme: minima
plugins:
  - jekyll-feed
